name: 'Context'

on:
  push:
  pull_request:
  issues:
  project:
  workflow_call:
  workflow_dispatch:


jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
    - name: View context attributes
      continue-on-error: true
      uses: actions/github-script@v5
      with:
        script: console.log(context)

    - name: github events
      continue-on-error: true
      run: |
      echo github.event.number = ${{ github.event.number  }}
      echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
      echo github.event.issue.number = ${{ github.event.issue.number }}
